Updated onscreen documentation
britzl/defold-input pull request #28
Opened 2022-04-02 18:57 UTC by Sandstedt

Before, it was a bit unclear, for a beginner, that this script need to require the `in.onscreen` module, and that the example code needs to be in a GUI script file to access the `gui` methods.

I also added .lua highlight on the code (that's what all the indention changes was for. Except for the first line with the `require`, all the example code is the same).

2022-04-03 11:12 UTC, britzl requested changes
Found a typo, but otherwise great improvements! Thanks.

2022-04-03 11:12 UTC, britzl commented on in/onscreen.md
> +In your .gui file's Properties, point the Script property to the [GUI script](https://defold.com/manuals/gui-script/) `onscreen.gui_script` that comes shipped with this library, and register and liss
lissen -> listen

2022-04-04 06:21 UTC, Sandstedt commented on in/onscreen.md
> +In your .gui file's Properties, point the Script property to the [GUI script](https://defold.com/manuals/gui-script/) `onscreen.gui_script` that comes shipped with this library, and register and liss
A nice catch. Fixed

2022-04-04 06:24 UTC, britzl approved these changes

2022-04-04 06:24 UTC, merged